# Generated by Django 3.1.5 on 2021-01-14 05:05

from django.db import migrations, models
import django.db.models.deletion
import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadOnFile', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to=file.models.get_upload_path)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='folder.folder')),
            ],
        ),
    ]
